#!/bin/sh
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
set -u

if [ $# -eq 0 ]; then
    >&2 echo "No arguments provided"
    exit 1
fi

script="$1"
exit_code="${2:-96}"
fail_if_not_present="${3:-y}"

if test -f "$script"; then
  shift  # Remove the first argument (script) from the list
  sh "$script" "$@"  # Pass the remaining arguments to the script

  if [ $? -ne 0 ]; then
    exit "$exit_code"
  fi
elif [ "$fail_if_not_present" = "y" ]; then
  >&2 echo "script not found: $script"
  exit 127
fi
